import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider, useAuth } from '../../components/AuthProvider';
import { supabase } from '../../lib/supabaseClient';
import { useRouter } from 'next/router';
import React from 'react';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  const { user, loading } = useAuth();
  const router = useRouter();

  const handleLogout = async () => {
    await supabase.auth.signOut();
    router.push('/auth/login');
  };

  return (
    <nav style={{
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      padding: '1rem 2rem', background: '#171717', color: '#fff', marginBottom: '2rem',
      boxShadow: '0 2px 8px rgba(0,0,0,0.07)'
    }}>
      <div style={{ fontWeight: 700, fontSize: 22, letterSpacing: 1 }}>Resume Tailor</div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
        <Link href="/dashboard" style={{ color: '#fff', textDecoration: 'none', fontWeight: 500 }}>Dashboard</Link>
        <Link href="/" style={{ color: '#fff', textDecoration: 'none', fontWeight: 500 }}>Home</Link>
        {!loading && user && (
          <>
            <span style={{ fontSize: 15, opacity: 0.8 }}>{user.email}</span>
            <button onClick={handleLogout} style={{
              background: '#fff', color: '#171717', border: 'none', borderRadius: 4,
              padding: '6px 16px', fontWeight: 600, cursor: 'pointer', marginLeft: 12
            }}>Logout</button>
          </>
        )}
        {!loading && !user && (
          <a href="/auth/login" style={{ color: '#fff', textDecoration: 'none', fontWeight: 500 }}>Login</a>
        )}
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
